server:
  error:
    include-stacktrace: on_trace_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_anime_sprinboot2?useSSL=false&createDatabaseIsNotExists=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update